### ISSUE TITLE
Add native support for account recovery

### ISSUE THREAD

**Issue by morleyzhi** [stellar/js-stellar-wallets#25]
One option to do this is to change the response signature of encrypter `encrypt` functions:

https://github.com/stellar/js-stellar-wallets/blob/master/src/types/keys.ts#L61

If we require that they all return a `recoveryValue` field of `any` type, and require that you can pass that value to `decrypt` instead of `password` and it'll unlock the key, that would allow people to use things like N-digit recovery strings or whatever to recover their account.

**Comment by morleyzhi** [comment]
It sounds like what we want to do is ask the Wallet provider to write a custom `Encrypter` library that uses a 16-word recovery code (or some other recovery token) as a seed to generate secret seeds. The Wallet provider will have to make sure that the recovery code is cryptographically secure and is generated in a sufficiently random way. 

If they do this, we won't need to add additional function arguments or return fields. @tomquisel am I describing this strategy correctly?

**Comment by jedmccaleb** [comment]
Do we need this is the first version of the wallet SDK?

**Comment by jedmccaleb** [comment]
I don't see why a 16 word thing that generates the seed is better than storing just the seed

**Comment by tomquisel** [comment]
@morleyzhi almost! Like you said, I think the preferred approach for recovery codes is to create a random recovery code that is shown to the user using [BIP39](https://github.com/bitcoinjs/bip39), and then deterministically generate their Stellar secret seed from that. What's nice is that this does not require a different `Encrypter` or any other change to the key manager SDK. Instead, it replaces the standard `Keypair.random()` call. The downside is that it can't handle users who want to import an existing account into a wallet, but I don't think that's an important use case to tackle now. Users rarely did that on StellarX, and it's easy to transfer funds from another account.

I'd imagine replacing `Keypair.random()` with something like this:

```javascript
function makeSeedAndRecoveryPhrase(userid) {
    const seed = nacl.randomBytes(16); // Stellar seeds are 32 bytes long, but having a 24-word recovery phrase is not great. 16 bytes is enough with the scrypt step below
    const recoveryPhrase = bip39.entropyToMnemonic(seed);
    const secret = await scrypt-async.scrypt(seed, userid, {opts...});
    const keypair = Keypair.fromRawEd25519Seed(secret);
    return {keypair, recoveryPhrase};
}
```

and then to recover the Stellar seed from the recovery phrase:
```javascript
function recoverKeypairFromPhrase(userid, recoveryPhrase) {
    const seed = bip39.mnemonicToSeedSync(recoveryPhrase);
    const secret = await scrypt-async.scrypt(seed, userid, {opts...});
    const keypair = Keypair.fromRawEd25519Seed(secret);
    return keypair;
}
```

@jedmccaleb it's not different from storing just the seed in any big way, but it also requires no work in the wallet SDK (unless we want to make the functions above available as utility functions).

The small reasons for using BIP39 vs asking users to store the seed:
- Ledger nano, Keybase, etc all use recovery phrases, so it's what users expect. They also must do it for good reason
- BIP39 includes checksum bits, so we can detect if the user has mis-entered their phrase
- If one or two characters in a recovery phrase gets corrupted, the user can probably figure out the words in the phrase anyway. This makes it good for paper wallets.
- It's easier for a person to write down without error
- there's a small security benefit: a casual hacker who discovers a recovery phrase may not be able to figure out the algorithm used to convert it into a seed.

**Comment by morleyzhi** [comment]
Since we don't want to change the API to add support for recovery (and support can be added without changing the API), we can close this.
