### ISSUE TITLE
Publish the library

### ISSUE THREAD

**Issue by morleyzhi** [stellar/js-stellar-wallets#30]
Publish this on NPM. The published library should point to built files.

- [X] Set up CI server
- [X] Enable publish-on-commit in CI
- [X] Test out importing the lib (possibly as a part of #31) -> https://github.com/stellar/js-stellar-wallet-app

**Comment by abuiles** [comment]
@morleyzhi thoughts on using an org scoped package name for this? I'll even say for other npm libraries maintained by SDF

https://docs.npmjs.com/creating-and-publishing-an-org-scoped-package

**Comment by morleyzhi** [comment]
Good idea, I'll make the org right now (if I can).

**Comment by abuiles** [comment]
@morleyzhi awesome, when publishing, remember to include this `--access public` otherwise you'll get trolled by npm.
