### ISSUE TITLE
Pull plans/keymanager/api.ts's KeyManager implementation into the main codebase

### ISSUE THREAD

**Issue by tomquisel** [stellar/js-stellar-wallets#37]
The KeyManager implementation in `plans/keymanager/api.ts` should be pulled into the SDK code so it can be used.

**Comment by morleyzhi** [comment]
Not sure I understand? https://github.com/stellar/js-stellar-wallets/blob/master/src/KeyManager.ts

**Comment by tomquisel** [comment]
Wow, apologies. I had an outdated local repo and thought it hadn't happened. Closing.
