### ISSUE TITLE
Improve error handling in the KeyManager

### ISSUE THREAD

**Issue by howardtw** [stellar/js-stellar-wallets#39]
As the introduction of `updateKeys` method and the behavior change of `storeKeys`, we might need a better way deal with the errors for keymanager. We now reject the promise if any of the keys is problematic for both methods. In addition, `changePassword` should use `updateKeys` now instead of `storeKeys`.

**Comment by morleyzhi** [comment]
@howardtw Is this ticket about updating the KeyManager interface or is it about improving error-handling in the KeyManager? If it's the former, can you give an example of a situation that does something unexpected in the current system, and what the expected behavior is?

**Comment by howardtw** [comment]
It's about improving the error handling. Now that both `storeKeys` and `updateKeys` would fail if any of the keys is problematic, so the caller will have to handle the promise reject in the case of a failure.

**Comment by morleyzhi** [comment]
I think the error-handling is what a dev would expect, so short of changing the API surface to flow around error cases, I'm leaving this as is.
