### ISSUE TITLE
Write plan for SEP-8 approval helpers

### ISSUE THREAD

**Issue by mikeyrf** [stellar/js-stellar-wallets#56]
Write an `ApprovalProvider` for SEP-8 regulated assets analogous to the `TransferProvider` implementation for SEP-6 compliance:

https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md

**Comment by morleyzhi** [comment]
That's a good idea. I'll turn this into a ticket to write that plan. I'm not sure when it'll land on our roadmap, as we're concentrating on getting a reference implementation up with account information and deposit / withdrawal, but this should go on the list!

**Comment by mikeyrf** [comment]
Great! This is pretty important for our roadmap, so I'm happy to contribute as long as it doesn't get in your way

**Comment by morleyzhi** [comment]
@mikeyrf It might help if you want to write a first draft of a plans doc:

https://github.com/stellar/js-stellar-wallets/tree/master/plans

It doesn't have to be the same format as what's in there. If you have any ideas for the feature set, the goals, and/or the API, you can put down as much or as little of that as possible, and we can use that to guide or thinking.

**Comment by mikeyrf** [comment]
Perfect. Sounds good to me
