### ISSUE TITLE
ApprovalProvider

### ISSUE THREAD

**Issue by morleyzhi** [stellar/js-stellar-wallets#58]
Implement SEP-8 support.

See also: 

Plan: https://github.com/stellar/js-stellar-wallets/blob/master/plans/sep8.md
PR + notes about API affordances: https://github.com/stellar/js-stellar-wallets/pull/57 
Old issue: https://github.com/stellar/js-stellar-wallets/issues/56

**Comment by morleyzhi** [comment]
@mikeyrf You mentioned this was useful for your roadmap, can you give me a sense of when you'd need this? I can't promise a timeline, but I'll do my best to line things up.

**Comment by mikeyrf** [comment]
@morleyzhi Thanks for asking. We're aiming for October to be up and running with our API/transfer server. Ideally, the js wallet sdk would SEP 8 included by then.

Is that reasonable timing? I can also help implement to speed things up, need be

**Comment by morleyzhi** [comment]
At first blush that should be plenty of time. Do you have a server up right now, or know of any working approval servers, for us to test against?

**Comment by mikeyrf** [comment]
Not yet for us but working on it. Hopefully within the next month or two.

I'd imagine Smartlands is planning on it from their recent [Medium post](https://medium.com/@smartlands/stellars-sep8-to-prevent-fragmentation-of-sdex-and-unlock-ultimate-liquidity-for-security-tokens-b1f838e44c98), although it's not clear if that's up and running yet either.

When would you need our server up by for testing?

**Comment by morleyzhi** [comment]
Next month or two would be fine, please add it to the ticket when it's up! Thanks!

**Comment by howardtw** [comment]
A [pre-release](https://github.com/stellar/js-stellar-wallets/releases/tag/v0.3.0-rc.5) that adds the SEP-8 support has been created.

I'm closing this issue for now. Feel free to create new issues if you find this release not fulfilling your need.
