### ISSUE TITLE
Change encrypted key format to encrypt the whole key

### ISSUE THREAD

**Issue by morleyzhi** [stellar/js-stellar-wallets#89]
See https://github.com/stellar/go/blob/master/services/keystore/spec.md

**Comment by fnando** [comment]
I've added a plan that enables that without changing the SDK too much. https://github.com/stellar/js-stellar-wallets/pull/91

**Comment by morleyzhi** [comment]
Closed in https://github.com/stellar/js-stellar-wallets/commit/0a4e603ea4ed8aa45e0e45c8228d86b9000142ab
